language: cpp
matrix:
  include:
  - os: linux
    dist: xenial
    compiler: clang
  - os: linux
    dist: xenial
    compiler: gcc
  - os: windows
    compiler: msvc
    
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release
