language: cpp
env:
  - BUILDTYPE=Release 
  #- BUILDTYPE=MinSizeRel
os: linux
dist: bionic
compiler:
  - gcc
  - clang
matrix:
  include:
  - os: windows
    compiler: cl.exe
    env: BUILDTYPE=Release CMAKE_GENERATOR="Visual Studio 15 2017" CMAKE_GENERATOR_PLATFORM=x64
  - os: windows
    compiler: cl.exe
    env: BUILDTYPE=Release CMAKE_GENERATOR="Visual Studio 15 2017" CMAKE_GENERATOR_PLATFORM=Win32
  #- os: windows
    #compiler: msvc
    #env: BUILDTYPE=MinSizeRel 
  
before_install:
  - if [ "$TRAVIS_COMPILER" = "gcc" ]; then sudo -E apt-get -yqq --no-install-suggests --no-install-recommends install g++-8 && CC=gcc-8 && CXX=g++-8; fi
  - if [ "$TRAVIS_COMPILER" = "clang" ]; then sudo -E apt-get -yqq --no-install-suggests --no-install-recommends install clang-7 llvm-7-dev && CC="/usr/bin/clang-7" && CXX="/usr/bin/clang++-7"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo -E apt -yqq install --fix-missing libstdc++-8-dev; fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILDTYPE ..
  - cmake --build . --config $BUILDTYPE --parallel 2
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then EXELOCATION="./$BUILDTYPE/msync.exe"; else EXELOCATION="./msync"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then TESTLOCATION="./tests/$BUILDTYPE/tests.exe"; else TESTLOCATION="./tests/tests"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then NETTESTLOCATION="./tests/$BUILDTYPE/net_tests.exe"; else NETTESTLOCATION="./tests/net_tests"; fi
  - $NETTESTLOCATION
  - $TESTLOCATION ~[long_run]
  - $TESTLOCATION [long_run]

after_success:
  - echo "Binary size:"
  - du -h $EXELOCATION
