language: cpp
matrix:
  include:
    - os: linux
    - dist: xenial
    - compiler: clang
  include:
    - os: linux
    - dist: xenial
    - compiler: gcc
  include:
    - os: windows
    - compiler: gcc

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release
