language: cpp
env:
  - BUILDTYPE=Release
  #- BUILDTYPE=MinSizeRel
os: linux
dist: bionic
compiler:
  - gcc
#  - clang # travis clang builds are failing with this weird 'undefined reference to pthread_atfork'
matrix:
  include:
  - os: windows
    compiler: msvc
    env: BUILDTYPE=Release 
  #- os: windows
    #compiler: msvc
    #env: BUILDTYPE=MinSizeRel 
  
before_install:
  - if [ "$TRAVIS_COMPILER" = "gcc" ]; then sudo -E apt-get -yq --no-install-suggests --no-install-recommends install g++-8 && CC=gcc-8 && CXX=g++-8; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt -yq install libssl-dev ; fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILDTYPE -DUSE_SYSTEM_CURL=OFF ..
  - cmake --build . --config $BUILDTYPE --parallel 2
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then EXELOCATION="./$BUILDTYPE/msync.exe"; else EXELOCATION="./msync"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then TESTLOCATION="./tests/$BUILDTYPE/tests.exe"; else TESTLOCATION="./tests/tests"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then NETTESTLOCATION="./tests/$BUILDTYPE/net_tests.exe"; else NETTESTLOCATION="./tests/net_tests"; fi

after_success:
  - echo "Binary size:"
  - du -h $EXELOCATION
  - $EXELOCATION help
  - $TESTLOCATION
  - $NETTESTLOCATION
  
